language: node_js
node_js:
  - "0.8"
install:
  - "bin/installDeps.sh"
before_script: 
  - "tests/frontend/travis/sauce_tunnel.sh"
env:
  global:
    - secure: zGX8AFKQnuh6WWLJw58WnRZiVQ4dIbN0gIQ0NpJIKmzQw2yQ+rqQEo2UoT5p\n+SSX/DJnU0yZzZ2RkiN8sabyY3e3Y2JhjO5GUTdoUxxB7ffCDLM4W1T8ckyl\nmSUW/ajrxMbGxruYbKQfepCRK6w4OoUsROYI0MpeoDo8ngxmcFw="
    - SAUCE_USER=pita
jdk:
  - oraclejdk6
notifications:
  email:
    - petermartischka@googlemail.com